DAYS_IN_A_YEAR = 365
DAYS_IN_A_MONTH = 30
FERTILISATION_RATE = 0.1

AGE_IN_DAYS_AT_MENARCHE = 3*DAYS_IN_A_MONTH
AGE_IN_DAYS_AT_MENOPAUSE = 10*DAYS_IN_A_YEAR
AGE_IN_DAYS_OF_FETUS_AT_BIRTH = DAYS_IN_A_MONTH
